name: mindful_reader
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_animate: ^4.0.0
  http: 1.2.2
  webview_flutter: ^2.0.10
  intl: 0.19.0
  flutter_svg: ^2.0.10+1
  video_player: ^2.9.1
  dio: ^5.6.0
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.4
  flutter_dotenv: ^5.1.0
  no_screenshot: ^0.3.1
  screen_protector: ^1.4.2+1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/Mindful-Reader.png"
  # image_path: "assets/images/Mindful-Reader.png"
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
    - assets/config/