name: Flutter Test and PR

on:
  push:
    branches:
      - dev  # Trigger the workflow on commits to the 'dev' branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test --coverage

  create-pull-request:
    runs-on: ubuntu-latest
    needs: test
    if: success()  # Only run if the previous job (test) succeeded

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Pull Request to Master
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: dev
        base: master
        title: 'Automated PR: Merge dev into master'
        body: |
          This pull request is automatically created by GitHub Actions after successful tests.
